name = "emoweather-worker"
main = "workers/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "emoweather-worker-production"
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Triggers - scheduled
[triggers]
crons = ["0 * * * *"]  # Run hourly
